name = "cf_ai_cloudflare_chat_memory"
main = "dist/worker.mjs"
compatibility_date = "2024-10-01"
account_id = "318ba91875b7eb2eda361fc741b71561"
workers_dev = true

[build]
command = "npm run build"

[durable_objects]
bindings = [
  { name = "CHAT_SESSIONS", class_name = "ChatSession" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatSession"]

[ai]
binding = "AI"

[vars]
AI_MODEL = "@cf/meta/llama-3-8b-instruct"
MAX_TURNS = 16
MAX_CHARS = 12000

[assets]
directory = "public"
